name: Scala Steward

# This workflow will launch everyday at 00:00
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  scala-steward:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    name: Scala Steward
    steps:
      - name: Get organization app token
        id: app-token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2.2.2
        with:
          app-id: ${{ vars.GET_TOKEN_APP_ID }}
          private-key: ${{ secrets.GET_TOKEN_APP_PRIVATE_KEY }}

      - uses: sbt/setup-sbt@v1

      - name: Scala Steward
        uses: scala-steward-org/scala-steward-action@v2.96.0
        with:
          github-token: ${{ steps.app-token.outputs.token }}
